spring.application.name=Air


# Database
spring.datasource.url=jdbc:mysql://4PB4UKmTqzHTgSp.root:Rrfi9A7LpfyNO9tu@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/air?sslMode=VERIFY_IDENTITY
spring.datasource.username=4PB4UKmTqzHTgSp.root
spring.datasource.password=Rrfi9A7LpfyNO9tu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

gemini.api.key={GEMINI_API_KEY}

